# Generated by Django 5.2.4 on 2025-07-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessApp', '0003_customer_credit_limit_customer_is_credit_approved_and_more'),
    ]

    operations = [
    ]
