# Generated by Django 5.2.4 on 2025-07-26 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessApp', '0004_auto_20250726_1309'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='original_amount',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='debtpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='debtpayment',
            name='created_by',
        ),
        migrations.AddField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original debt amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
