# Generated by Django 5.2.4 on 2025-07-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessApp', '0005_remove_debt_original_amount_and_more'),
    ]

    operations = [
    ]
